# Generated by Django 4.2.20 on 2025-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_created_at_post_date_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
