services:
  - type: web
    name: simple-django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn simple_django.wsgi:application --bind 0.0.0.0:10000"

    postDeployCommand: "python manage.py migrate"
